name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ESP32 board support
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile the sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 \
            --output-dir build \
            model_test_INMP441/model_test_INMP441.ino

      - name: Upload firmware binary
        uses: actions/upload-artifact@v3
        with:
          name: firmware-bin
          path: build/*.bin
