name: Compile ESP32 INO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 your_sketch.ino

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-ino
          path: ./build
